defmodule JidoGralkor.PluginTest do
  use ExUnit.Case, async: false

  import ExUnit.CaptureLog

  alias Gralkor.Client.InMemory
  alias Gralkor.Message
  alias Jido.Signal
  alias JidoGralkor.Plugin

  setup_all do
    {:ok, _applications} = Application.ensure_all_started(:jido_signal)
    :ok
  end

  setup do
    InMemory.reset()
    :ok
  end

  defp agent(id, opts) do
    thread_id = Keyword.get(opts, :thread_id, "thr-default")
    request_traces = Keyword.get(opts, :request_traces, %{})
    requests = Keyword.get(opts, :requests, %{})
    agent_name = Keyword.get(opts, :agent_name, "TestAgent")
    user_name = Keyword.get(opts, :user_name, "Eli")

    state =
      %{
        __strategy__: %{request_traces: request_traces},
        requests: requests,
        __memory__: %{agent_name: agent_name},
        user_name: user_name
      }
      |> maybe_put(:__thread__, if(thread_id, do: %{id: thread_id}, else: nil))

    %{id: id, state: state}
  end

  defp maybe_put(map, _k, nil), do: map
  defp maybe_put(map, k, v), do: Map.put(map, k, v)

  defp context(agent), do: %{agent: agent}

  test "registers MemorySearch, MemoryAdd, MemoryBuildIndices, and MemoryBuildCommunities as plugin actions, exposed via the autogenerated `actions/0` for consumers to pass to `tools:`" do
    assert Plugin.actions() == [
             JidoGralkor.Actions.MemorySearch,
             JidoGralkor.Actions.MemoryAdd,
             JidoGralkor.Actions.MemoryBuildIndices,
             JidoGralkor.Actions.MemoryBuildCommunities
           ]
  end

  test "a consumer agent that mounts the plugin compiles (no Jido route conflicts)" do
    instance = Jido.Plugin.Instance.new({Plugin, %{agent_name: "Test"}})
    routes = Jido.Plugin.Routes.expand_routes(instance)
    assert {:ok, _resolved} = Jido.Plugin.Routes.detect_conflicts(routes)
  end

  test "the session_id is the Jido thread id — the plugin does not mint its own" do
    signal = Signal.new!("ai.react.query", %{query: "q"}, source: "/test")

    assert {:ok, {:continue, %Signal{data: data}}} =
             Plugin.handle_signal(signal, context(agent("user-1", thread_id: "thr-exact")))

    assert data.tool_context.session_id == "thr-exact"
  end

  test "mount/2 returns {:ok, %{agent_name: ...}} when given a non-blank :agent_name opt" do
    assert {:ok, %{agent_name: "Susu"}} =
             Plugin.mount(%{id: "user-1", state: %{}}, agent_name: "Susu")
  end

  test "mount/2 raises ArgumentError when :agent_name is missing" do
    assert_raise ArgumentError, fn ->
      Plugin.mount(%{id: "user-1", state: %{}}, [])
    end
  end

  test "mount/2 raises ArgumentError when :agent_name is blank" do
    assert_raise ArgumentError, fn ->
      Plugin.mount(%{id: "user-1", state: %{}}, agent_name: "  ")
    end
  end

  describe "when an agent turn begins, when a thread has committed to agent state" do
    test "the thread's session_id and agent_name are planted on the signal's tool_context" do
      signal = Signal.new!("ai.react.query", %{query: "hi"}, source: "/test")

      assert {:ok, {:continue, %Signal{data: data}}} =
               Plugin.handle_signal(signal, context(agent("user-abc", thread_id: "thr-xyz")))

      assert data.tool_context.session_id == "thr-xyz"
      assert data.tool_context.agent_name == "TestAgent"
    end

    test "the plugin does not call recall on its own (recall is the LLM's job)" do
      signal = Signal.new!("ai.react.query", %{query: "hi"}, source: "/test")

      Plugin.handle_signal(signal, context(agent("user-abc", thread_id: "thr-xyz")))

      assert InMemory.recalls() == []
    end

    test "the query is left untouched on the signal" do
      signal = Signal.new!("ai.react.query", %{query: "hello"}, source: "/test")

      assert {:ok, {:continue, %Signal{data: data}}} =
               Plugin.handle_signal(signal, context(agent("user-abc", thread_id: "thr-xyz")))

      assert data.query == "hello"
    end
  end

  describe "when an agent turn begins, when no thread has committed yet" do
    test "only the configured agent_name is planted on tool_context (no session_id)" do
      signal = Signal.new!("ai.react.query", %{query: "hi"}, source: "/test")

      assert {:ok, {:continue, %Signal{data: data}}} =
               Plugin.handle_signal(signal, context(agent("user-abc", thread_id: nil)))

      assert data.tool_context.agent_name == "TestAgent"
      refute Map.has_key?(data.tool_context, :session_id)
    end

    test "the plugin still does not call recall" do
      signal = Signal.new!("ai.react.query", %{query: "hi"}, source: "/test")

      Plugin.handle_signal(signal, context(agent("user-abc", thread_id: nil)))

      assert InMemory.recalls() == []
    end
  end

  describe "when an agent turn completes" do
    test "the turn is sent to Gralkor for capture as canonical messages with the thread's session_id and the principal's group_id" do
      InMemory.set_capture(:ok)

      events = [
        %{kind: :llm_completed, data: %{text: "thinking"}},
        %{kind: :tool_completed, data: %{tool_name: "memory_search", result: "..."}}
      ]

      request_id = "req-xyz"

      ag =
        agent("user-42",
          thread_id: "thr-42",
          request_traces: %{request_id => %{events: events, truncated?: false}},
          requests: %{
            request_id => %{query: "what did I say?", status: :pending, result: nil}
          }
        )

      signal =
        Signal.new!(
          "ai.request.completed",
          %{request_id: request_id, result: "you said hi"},
          source: "/test"
        )

      assert {:ok, :continue} = Plugin.handle_signal(signal, context(ag))

      assert [[session_id, group_id, _agent_name, _user_name, messages]] = InMemory.captures()
      assert session_id == "thr-42"
      assert group_id == "user_42"
      assert [%Message{role: "user", content: "what did I say?"} | rest] = messages
      assert Enum.any?(rest, &match?(%Message{role: "behaviour"}, &1))
      assert List.last(messages) == %Message{role: "assistant", content: "you said hi"}
    end

    test "the user_name read from agent.state[:user_name] is forwarded to capture" do
      InMemory.set_capture(:ok)
      request_id = "req-username"

      ag =
        agent("user-42",
          user_name: "Eli",
          thread_id: "thr-42",
          request_traces: %{
            request_id => %{
              events: [%{kind: :llm_completed, data: %{}}],
              truncated?: false
            }
          },
          requests: %{request_id => %{query: "hi", status: :pending, result: nil}}
        )

      signal =
        Signal.new!(
          "ai.request.completed",
          %{request_id: request_id, result: "yo"},
          source: "/test"
        )

      Plugin.handle_signal(signal, context(ag))

      assert [[_session_id, _group_id, _agent_name, "Eli", _messages]] = InMemory.captures()
    end

    test "if agent.state[:user_name] is missing then capture raises ArgumentError" do
      InMemory.set_capture(:ok)
      request_id = "req-no-user"

      ag = %{
        id: "user-42",
        state: %{
          __strategy__: %{
            request_traces: %{
              request_id => %{
                events: [%{kind: :llm_completed, data: %{}}],
                truncated?: false
              }
            }
          },
          requests: %{request_id => %{query: "hi", status: :pending, result: nil}},
          __memory__: %{agent_name: "TestAgent"},
          __thread__: %{id: "thr-42"}
        }
      }

      signal =
        Signal.new!(
          "ai.request.completed",
          %{request_id: request_id, result: "yo"},
          source: "/test"
        )

      assert_raise ArgumentError, ~r/user_name/, fn ->
        Plugin.handle_signal(signal, context(ag))
      end
    end

    test "if agent.state[:user_name] is blank then capture raises ArgumentError" do
      InMemory.set_capture(:ok)
      request_id = "req-blank-user"

      ag =
        agent("user-42",
          user_name: "   ",
          thread_id: "thr-42",
          request_traces: %{
            request_id => %{
              events: [%{kind: :llm_completed, data: %{}}],
              truncated?: false
            }
          },
          requests: %{request_id => %{query: "hi", status: :pending, result: nil}}
        )

      signal =
        Signal.new!(
          "ai.request.completed",
          %{request_id: request_id, result: "yo"},
          source: "/test"
        )

      assert_raise ArgumentError, ~r/user_name/, fn ->
        Plugin.handle_signal(signal, context(ag))
      end
    end
  end

  describe "when an agent turn fails" do
    test "the turn is captured with the failure surfaced as a terminal 'request failed: …' behaviour message" do
      InMemory.set_capture(:ok)
      request_id = "req-fail"

      ag =
        agent("user-01",
          thread_id: "thr-fail",
          request_traces: %{
            request_id => %{events: [%{kind: :llm_completed, data: %{}}], truncated?: false}
          },
          requests: %{
            request_id => %{query: "original question", status: :pending, result: nil}
          }
        )

      signal =
        Signal.new!("ai.request.failed", %{request_id: request_id, error: :boom}, source: "/test")

      Plugin.handle_signal(signal, context(ag))

      assert [[session_id, _group_id, _agent_name, _user_name, messages]] = InMemory.captures()
      assert session_id == "thr-fail"

      user_msg = Enum.find(messages, &(&1.role == "user"))
      assert user_msg.content == "original question"

      assert List.last(messages) == %Message{
               role: "behaviour",
               content: "request failed: :boom"
             }

      refute Enum.any?(messages, &(&1.role == "assistant"))
    end

    test "first-turn failure with no thread committed skips capture and logs a warning" do
      InMemory.set_capture(:ok)
      request_id = "req-first-fail"

      ag =
        agent("user-01",
          thread_id: nil,
          request_traces: %{
            request_id => %{events: [%{kind: :llm_completed, data: %{}}], truncated?: false}
          },
          requests: %{request_id => %{query: "q", status: :pending, result: nil}}
        )

      signal =
        Signal.new!("ai.request.failed", %{request_id: request_id, error: :boom}, source: "/test")

      log =
        capture_log(fn ->
          assert {:ok, :continue} = Plugin.handle_signal(signal, context(ag))
        end)

      assert InMemory.captures() == []
      assert log =~ "[jido_gralkor] skipping capture"
      assert log =~ "user-01"
      assert log =~ "JIDO_CHANGE_SUGGESTIONS.md"
    end
  end

  describe "when a signal of any other type arrives" do
    test "handle_signal/2 returns {:ok, :continue} with no captures and no recalls" do
      ag = agent("user-other", thread_id: "thr-other")
      signal = Signal.new!("ai.llm.delta", %{token: "x"}, source: "/test")

      assert {:ok, :continue} = Plugin.handle_signal(signal, context(ag))
      assert InMemory.captures() == []
      assert InMemory.recalls() == []
    end
  end

  describe "when the completed turn has no events in its request trace" do
    test "no capture is sent" do
      InMemory.set_capture(:ok)
      request_id = "req-empty"

      ag =
        agent("user-01",
          thread_id: "thr-empty",
          request_traces: %{request_id => %{events: [], truncated?: false}},
          requests: %{request_id => %{query: "q", status: :pending, result: nil}}
        )

      signal =
        Signal.new!("ai.request.completed", %{request_id: request_id, result: "a"},
          source: "/test"
        )

      Plugin.handle_signal(signal, context(ag))

      assert InMemory.captures() == []
    end
  end

  describe "if capture fails" do
    test "the callback raises" do
      InMemory.set_capture({:error, :gralkor_unreachable})
      request_id = "req-err"

      ag =
        agent("user-01",
          thread_id: "thr-err",
          request_traces: %{
            request_id => %{events: [%{kind: :llm_completed, data: %{}}], truncated?: false}
          },
          requests: %{request_id => %{query: "q", status: :pending, result: nil}}
        )

      signal =
        Signal.new!("ai.request.completed", %{request_id: request_id, result: "a"},
          source: "/test"
        )

      assert_raise RuntimeError, ~r/Gralkor capture failed.*gralkor_unreachable/, fn ->
        Plugin.handle_signal(signal, context(ag))
      end
    end
  end
end
